### ISSUE TITLE
[BUG] iOS 14.5 Public Beta

### ISSUE THREAD

**Issue by karbowiak** [johannes-schliephake/nextcloud-passwords-ios#28] opened 2021-02-20 18:22 UTC
Hi there, there seems to be a weird issue going on with the latest public beta (happened in beta1 and beta2).

I can reproduce it on an iPad Pro and an iPhone 12 Mini.

Basically, the password box that comes up never unblurs.. i've attached a video:

https://user-images.githubusercontent.com/337661/108604894-ec403000-73b0-11eb-9e61-1979e2d0f130.mp4

**Comment by johannes-schliephake** [comment] 2021-02-21 18:16
Thanks for catching this one so early!

Unfortunately, this seems to be an issue with the iOS 14.5 beta. I can narrow the issue down to network requests freezing during TLS evaluation. A post on Apple's developer forums describes similar issues: [https://developer.apple.com/forums/thread/674277](https://developer.apple.com/forums/thread/674277)

I will keep the issue open for now until the iOS beta is fixed or a solution is available.

**Comment by karbowiak** [comment] 2021-02-22 21:55
@johannes-schliephake alrighty! i know running iOS beta means some apps do weird things - i'll survive for now, just a bit cumbersome to open the passwords app and copy/pasting everything :D

**Comment by johannes-schliephake** [comment] 2021-03-02 23:10
I can confirm that the issue is fixed in the latest iOS developer beta (14.5 beta 3). It might take a few days until the public beta is updated as well, but fortunately, Apple acted fast on this one.

**Comment by karbowiak** [comment] 2021-03-03 14:48
@johannes-schliephake awesome! i'll quietly keep on weeping while i wait for the new Public Beta :D /jk

Thanks tho <3

**Comment by karbowiak** [comment] 2021-03-04 12:32
Hello again @johannes-schliephake, seems it's still a bug with Public Beta 3 as well (14.5 - 18E5164h)
Tested on iPhone 12 Mini and iPad Pro 2018 (or is it 2019? i can't remember, the new model atleast)

https://user-images.githubusercontent.com/337661/109959846-51b4ea80-7ce8-11eb-8110-8b953b448673.mp4

Public Beta 3 released earlier today

**Comment by johannes-schliephake** [comment] 2021-03-05 18:16
I'm sorry to hear that!

Sadly, I can't reproduce the issue with the developer beta. I even tried the exact same setup with Apollo. I'm not 100% sure if the developer beta and public beta are the exact same builds. It might be that the TLS bug is fixed for developers but not yet in the public beta.

A few questions: Do you have biometrics set up? Do you have a passcode set up? And does the issue occur everywhere or just in Apollo?

**Comment by karbowiak** [comment] 2021-03-05 19:37
@johannes-schliephake 

No worries my dude - just requires a bit of copy/pasting, and yeah - the public betas might actually be one version behind the devleoper betas - but that might also be entirely fabricated on my part :D

But to answer your questions:

Biometrics: yes, face id also on the app itself - works perfectly if i open the app directly
Passcode: yes, required for face id as fallback
Issue occurs everywhere the app gets invoked - be it Apollo, Reddit, Facebook, Twitter, Safari etc.
Only place it works perfectly is when the app itself is opened :)

If you want i can make you a video and email it to you directly (will be showing the password app itself and whatnots - rather not share that with the entire world :D)

**Comment by johannes-schliephake** [comment] 2021-03-07 14:01
Your answers helped me out a lot!

I found three other issues resulting in the same problem. Let's just say that SwiftUI has a few crazy inconsistencies when launched from a password input.

I hope the biometric authentication is working reliably from now on.

**Closed** 2021-03-07 14:02 UTC
Labels: bug
