### ISSUE TITLE
Multiple Accounts

### ISSUE THREAD

**Issue by crustulumtheoneandonly** [johannes-schliephake/nextcloud-passwords-ios#254] opened 2023-05-26 11:32 UTC
### Feature Description

How about adding multi Account Support? Like the nextcloud files App, so you can Connect to multiple nc instances :)

### Rationale

I think many people have a private nextcloud, a work / business nextcloud and maybe a third nextcloud from a different organisation.

**Comment by johannes-schliephake** [comment] 2023-05-27 14:36
Duplicate of #128. I'm going to write some details over there :)

**Closed by johannes-schliephake** 2023-05-27 14:36 UTC
Labels: feature
