### ISSUE TITLE
Add Support for Managed AppConfig

### ISSUE THREAD

**Issue by idominiki** [johannes-schliephake/nextcloud-passwords-ios#235] opened 2022-11-30 13:25 UTC
**Current Status**
Currently, users must enter their server details.

**Feature Description**
It would be great if the Server URL and username can be configured through managed AppConfig

**Additional context**
https://developer.jamf.com/developer-guide/docs/managed-app-configuration

**Comment by johannes-schliephake** [comment] 2022-11-30 21:43
Duplicate of #115. Let's talk over there!

**Closed by johannes-schliephake** 2022-11-30 21:43 UTC
