### ISSUE TITLE
UI issues in auto fill dialog

### ISSUE THREAD

**Issue by hellojaccc** [johannes-schliephake/nextcloud-passwords-ios#103] opened 2021-08-07 13:32 UTC
![image](https://user-images.githubusercontent.com/71537512/128601888-b0c19fa2-cabf-4cdf-98f2-ced306181005.png)

When i search in auto fill dialog, this broken keyboard appears

iOS 14.7 
iPhone SE 2

**Comment by hellojaccc** [comment] 2021-08-07 13:51
![image](https://user-images.githubusercontent.com/71537512/128602425-882a7347-be97-4c4c-a645-e1594b25c3b8.png)

When i closed keyboard.

**Comment by johannes-schliephake** [comment] 2021-08-07 14:01
What happens if you open the keyboard again after closing it once? I'm aware of a few issues with SwiftUI in Apple's password extensions, but this one looks new to me. (Also I couldn't reproduce it yet)

**Comment by hellojaccc** [comment] 2021-08-07 14:02
> What happens if you open the keyboard again after closing it once? I'm aware of a few issues with SwiftUI in Apple's password extensions, but this one looks new to me. (Also I couldn't reproduce it yet)

First issue (broken keyboard) was not fixed by re opening keyboard.

**Comment by johannes-schliephake** [comment] 2021-08-09 20:43
Ok, I'm looking into it. But it might take a bit until I can reproduce and understand this bug,

**Comment by johannes-schliephake** [comment] 2021-09-22 21:00
While I was able to reproduce similar, albeit not that extreme layout issues, it looks like they are fixed on iOS 15. This probably means that this was an issue on Apple's side. Finding fixes for iOS 14 won't make sense, if it's even possible.
Just to make sure I'll still leave this issue open for a bit.

**Closed** 2021-11-07 20:15 UTC
Labels: bug
